services:
  postgres:
    image: postgres:latest
    container_name: nextweb-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next-web
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
